decision: False     # 是否启动导航的规划器。
model: True    # 是否启动仿真模式。
world: rmul_2025    # 指定导航世界。
namespace: red_standard_robot1   # 指定机器人的命名空间。
slam: False    # 是否启用SLAM（同时定位与地图构建）。
use_robot_state_pub: False    # 是否使用机器人TF状态发布器。
use_rviz: True    # 是否使用RViz进行可视化。
